# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IX9A0WRQuhHnvtJ5dKWIfW6OkFAoGf3U
"""

print("123")